from utils import cached

LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
TOTAL_LETTERS = len(LETTERS)
assert TOTAL_LETTERS == 26

def cezar(offset):
	alphabet = {letter: LETTERS[(i - offset) % TOTAL_LETTERS] for i, letter in enumerate(LETTERS)}
	def cipher(text):
		return ''.join(alphabet.get(char, char) for char in text)
	return cipher

@cached
def fib(n):
	if n == 1:
		return 1
	elif n == 2:
		return 2
	else:
		return fib(n - 2) + fib(n - 1)

# console.log(JSON.stringify(Array.prototype.map.call(document.querySelectorAll('.container li'), function(li) {return li.innerText})));
WORDS = ["TVCWPDBMJTBUJPO","UWNRJWTKBCVKQPU","FRQWUDFWDELOLWB","INAJWYNXXJRJSYX","ACJKIBMOWZQHQVO","PBASRFFVBANEVRF","XDIZHDXMJBMVKCT","NCOIKQWCAVMAAMA","FRQWUDFWDELOLWB","PYLYETZXZCASTPD","VMRFCGHOHWQOZZM","RTAUNBZKHRZSHNM","VADHVFVGBEVNYYL","YUEBDABADFUAZQP","OSDQHCNOGHKHRSR","DNLYOLWTKLETZYD","YBKMEVYECXOCCOC","XDIZHDXMJBMVKCT","UFSTUMYMFQRNYNX","SUCCESSLESSNESS","TWYMTUFJINHFQQD","JSFSYNTRTWUMNJX","KQQBKXNSCOWOXDC","TJSXDBTIGXRPAAN","RTBBDRRKDRRMDRR","IZHFOGHFIQHIFOZ","ERZBARGVMNGVBAF","ESFBNMFTTOFTTFT","ASUOJSFHSPFOHSG","DKTGJIXAXOPIXDC","IRUHQVLFDOLWLHV","VAKAFUDAFSLAGFK","YDNZHWVMFVODJIN","IVOEBSYBGNGVBAF","KPIUJMZTIQVAPQX","YDNDIXGDIVODJIN","RYHUXWLOLCDWLRQ","GLOSGQGRMPGYJJW","DPVOUFSCBMBODFT","RTABZSDFNQHYHMF","CONDESCENDINGLY","BGZLADQKZHMRGHO","DTCHNLDSQHBZKKX","SJRPYQRPSARSPYJ","OBQROKXYFIFQFBP","WDJNTNOZHVODNON","TJSUZQVSULQDAKE","FPNAQNYVMNGVBAF","MDIWTXYFYNHFQQD","VAKUGFLAFMALAWK","KLOQEBOIFKBPPBP","TMRAPJHIGPIXDCH","NDAZOTAEOABUOMX","BHHSBOEJTFNFOUT","PBAGENCBFVGVBAF","QCBHFODCGWHWCBG","CJUVNJOJABUJPOT","RDCUTHHXDCPGXTH","IJUHUEJOFYSQBBO","MJRFLLQZYNSFYJX","YMZVHGZNNIZNNZN","AXIOMATIZATIONS","JMOCJKVZYDXVGGT","YDNVAADMHVODJIN","JXUHYECEHFXYICI","LITZXLETKLETZYD","VOJOGPSNBUJWFMZ","ZADFTQDXUZQEEQE","ERGHEANOVYVGVRF","UHAQNEKNSZSHNMR","PUHQDFUEEQYQZFE","CPZCNSPDECLETZY","LOXZRILRPKBPPBP","NCOIKQWCAVMAAMA","YMJWNTRTWUMNXRX","OEBAPUBFPBCVPNY","MFAFXGJESLANWDQ","HTSIJXHJSINSLQD","PQBOBLQVMFZXIIV","HQTGPUKECNKVKGU","OSDQHCNOGHKHRSR","CSBDIZEBDUZMJTN","PANOPHTHALMITIS","QIPUPJPOJABUJPO","TVMQIVSJABUJPOT","RCPVKUQETCVKECN","SDQWLVRFUDWLFDO","INXJRGFWPFYNTSX","LQAKWVBQVCQBQMA","RKPYNHFGENGVBAF","MZJMXCZNOMVODJI","PMUIOOTCBQVIBMA","UHPRQHWLCDWLRQV","XPECZAZWTELYLEP","ASHFCDCZWHOBOHS","CHRZEEHQLZSHNMR","CUBGBVBAVMNGVBA","NUFGYUZULMFUAZE","LHROQNONQSHNMDC","NZFYEPCMLWLYNPD","WOQKFOBDOLBKDOC"]

from collections import defaultdict
decoded_words = defaultdict(lambda: 0)

for n, word in enumerate(WORDS, 1):
	offset = fib(n)
	cipher = cezar(offset)
	decoded_word = cipher(word)
	decoded_words[decoded_word] += 1

for decoded_word, count in decoded_words.iteritems():
	if count > 1:
		continue
	print decoded_word
